-- 如果表存在，则删除它
DROP TABLE IF EXISTS file_meta;

-- 创建表，如果它不存在
CREATE TABLE IF NOT EXISTS file_meta (
    NAME VARCHAR(100) NOT NULL,
    PATH VARCHAR(200) NOT NULL,
    SIZE BIGINT NOT NULL,
    LAST_MODIFIED_TIME DATE NOT NULL,
    IS_DIRECTORY BOOLEAN NOT NULL,
    PIN_YIN_FIRST_CHARACTER VARCHAR(50) NOT NULL,
    PIN_YIN_FULL_NAME VARCHAR(500) NOT NULL
);
